-- ============================================================================
--  questions-bank.sql — 440 NEW trivia questions (the big question bank)
--
--  Adds 110 questions to EACH of the 4 categories: Science, Math, Football,
--  History. Combined with seed.sql's 40, the bank holds 480 questions.
--
--  HOW TO USE:
--    Run this AFTER schema.sql + seed.sql (or setup-demo.sql for an existing
--    project). Paste into supabase.com -> SQL Editor -> RUN.
--
--  SAFE TO RE-RUN: each category only fills in when it has fewer than 100
--  questions, so running this file twice (or after the seed) never duplicates.
--
--  Every match now guarantees category variety: the matchmaking RPCs draw
--  from ALL FOUR categories in every match (see the updated join_matchmaking
--  / create_challenge functions in schema.sql / setup-demo.sql / friends-bots.sql).
-- ============================================================================


-- ============================================================================
--  SCIENCE (110)
-- ============================================================================
do $$
begin
  if (select count(*) from public.questions where category = 'Science') < 100 then
    insert into public.questions (category, question, options, correct_index) values

('Science', 'What is the closest planet to the Sun?', ARRAY['Mercury', 'Venus', 'Earth', 'Mars'], 0),
('Science', 'What gas makes up about 78% of Earth''s atmosphere?', ARRAY['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Argon'], 1),
('Science', 'What is the largest organ of the human body?', ARRAY['Liver', 'Skin', 'Brain', 'Heart'], 1),
('Science', 'What is the study of weather called?', ARRAY['Geology', 'Astronomy', 'Meteorology', 'Ecology'], 2),
('Science', 'What is the boiling point of water at sea level?', ARRAY['90°C', '100°C', '110°C', '120°C'], 1),
('Science', 'How many hearts does an octopus have?', ARRAY['One', 'Two', 'Three', 'Four'], 2),
('Science', 'What is the smallest unit of life?', ARRAY['Atom', 'Molecule', 'Cell', 'Tissue'], 2),
('Science', 'What is the most abundant element in the universe?', ARRAY['Helium', 'Oxygen', 'Carbon', 'Hydrogen'], 3),
('Science', 'Which planet is famous for its spectacular rings?', ARRAY['Jupiter', 'Neptune', 'Saturn', 'Uranus'], 2),
('Science', 'Which part of the cell controls its activities?', ARRAY['Cytoplasm', 'Nucleus', 'Membrane', 'Ribosome'], 1),
('Science', 'What is the scientific study of birds called?', ARRAY['Entomology', 'Ichthyology', 'Ornithology', 'Herpetology'], 2),
('Science', 'How many bones are in a single adult human hand?', ARRAY['24', '27', '30', '21'], 1),
('Science', 'What is the approximate speed of sound in air?', ARRAY['343 m/s', '100 m/s', '700 m/s', '1200 m/s'], 0),
('Science', 'Which planet rotates on its side?', ARRAY['Neptune', 'Uranus', 'Saturn', 'Mercury'], 1),
('Science', 'Which vitamin does sunlight help the body produce?', ARRAY['Vitamin A', 'Vitamin B12', 'Vitamin C', 'Vitamin D'], 3),
('Science', 'What is the hardest natural substance on Earth?', ARRAY['Quartz', 'Diamond', 'Gold', 'Iron'], 1),
('Science', 'What type of animal is a dolphin?', ARRAY['Fish', 'Reptile', 'Mammal', 'Amphibian'], 2),
('Science', 'What is the freezing point of water in Fahrenheit?', ARRAY['0°F', '32°F', '100°F', '212°F'], 1),
('Science', 'Which planet is known as the Morning Star?', ARRAY['Venus', 'Mars', 'Mercury', 'Jupiter'], 0),
('Science', 'What do honeybees collect to make honey?', ARRAY['Pollen', 'Nectar', 'Water', 'Sap'], 1),
('Science', 'What is the chemical symbol for gold?', ARRAY['Go', 'Ag', 'Au', 'Gd'], 2),
('Science', 'What is the scientific study of plants called?', ARRAY['Zoology', 'Botany', 'Geology', 'Astronomy'], 1),
('Science', 'Which gas do plants release during photosynthesis?', ARRAY['Hydrogen', 'Carbon dioxide', 'Nitrogen', 'Oxygen'], 3),
('Science', 'What is the largest mammal in the world?', ARRAY['Elephant', 'Blue whale', 'Giraffe', 'Orca'], 1),
('Science', 'How many teeth does a healthy adult human have?', ARRAY['28', '32', '36', '30'], 1),
('Science', 'What is the center of an atom called?', ARRAY['Proton', 'Electron shell', 'Nucleus', 'Orbit'], 2),
('Science', 'Which blood type is the universal donor?', ARRAY['O negative', 'AB positive', 'A positive', 'B negative'], 0),
('Science', 'What is the study of the Earth''s solid structure called?', ARRAY['Biology', 'Meteorology', 'Astronomy', 'Geology'], 3),
('Science', 'What is the largest land animal?', ARRAY['African elephant', 'White rhino', 'Giraffe', 'Hippopotamus'], 0),
('Science', 'What is the chemical symbol for sodium?', ARRAY['So', 'Na', 'Sd', 'Nm'], 1),
('Science', 'How long does it take Earth to orbit the Sun?', ARRAY['24 hours', '30 days', '365 days', '7 days'], 2),
('Science', 'What is the brightest star in Earth''s night sky?', ARRAY['Betelgeuse', 'Polaris', 'Vega', 'Sirius'], 3),
('Science', 'What is the main ingredient used to make glass?', ARRAY['Clay', 'Sand', 'Lime', 'Salt'], 1),
('Science', 'Which blood cells fight infection?', ARRAY['Red blood cells', 'White blood cells', 'Platelets', 'Plasma'], 1),
('Science', 'What is a baby frog called?', ARRAY['Pup', 'Tadpole', 'Cub', 'Chick'], 1),
('Science', 'Which metal is liquid at room temperature?', ARRAY['Iron', 'Copper', 'Mercury', 'Aluminum'], 2),
('Science', 'What is the largest internal organ in the human body?', ARRAY['Liver', 'Lungs', 'Stomach', 'Kidneys'], 0),
('Science', 'What do we call animals that only eat plants?', ARRAY['Carnivores', 'Omnivores', 'Herbivores', 'Insectivores'], 2),
('Science', 'What is the name for a group of wolves?', ARRAY['Pack', 'Herd', 'Flock', 'Pride'], 0),
('Science', 'What natural phenomenon causes ocean tides?', ARRAY['Wind', 'Earthquakes', 'The Moon''s gravity', 'The Sun''s heat'], 2),
('Science', 'Which planet has the Great Red Spot?', ARRAY['Saturn', 'Jupiter', 'Mars', 'Neptune'], 1),
('Science', 'What is the chemical formula for table salt?', ARRAY['KCl', 'NaCl', 'CaCl2', 'MgO'], 1),
('Science', 'How many legs does an insect have?', ARRAY['Eight', 'Four', 'Six', 'Ten'], 2),
('Science', 'What is the study of ancient life through fossils called?', ARRAY['Archaeology', 'Anthropology', 'Geology', 'Paleontology'], 3),
('Science', 'What is the unit of electric current?', ARRAY['Volt', 'Watt', 'Ampere', 'Ohm'], 2),
('Science', 'Which organ pumps blood around the body?', ARRAY['Brain', 'Lungs', 'Liver', 'Heart'], 3),
('Science', 'What is the outermost layer of the Earth called?', ARRAY['Mantle', 'Crust', 'Core', 'Magma'], 1),
('Science', 'What kind of scientist studies stars and planets?', ARRAY['Geologist', 'Botanist', 'Entomologist', 'Astronomer'], 3),
('Science', 'What is the fastest land animal?', ARRAY['Lion', 'Cheetah', 'Horse', 'Greyhound'], 1),
('Science', 'What is the chemical symbol for iron?', ARRAY['Fe', 'Ir', 'I', 'F'], 0),
('Science', 'How many eyes does a honeybee have?', ARRAY['Two', 'Three', 'Five', 'Eight'], 2),
('Science', 'What is the longest bone in the human body?', ARRAY['Tibia', 'Femur', 'Humerus', 'Radius'], 1),
('Science', 'Which of these is NOT a state of matter?', ARRAY['Solid', 'Liquid', 'Energy', 'Gas'], 2),
('Science', 'What is the name of the galaxy that contains Earth?', ARRAY['Andromeda', 'Milky Way', 'Sombrero', 'Whirlpool'], 1),
('Science', 'What process do plants use to make their own food?', ARRAY['Respiration', 'Digestion', 'Fermentation', 'Photosynthesis'], 3),
('Science', 'What is the hottest planet in our solar system?', ARRAY['Mercury', 'Mars', 'Venus', 'Jupiter'], 2),
('Science', 'What is the pH of pure water?', ARRAY['7', '1', '10', '14'], 0),
('Science', 'What is the study of the origin and structure of the universe called?', ARRAY['Cartography', 'Cosmology', 'Ethology', 'Geology'], 1),
('Science', 'Which organs filter blood to produce urine?', ARRAY['Liver', 'Bladder', 'Kidneys', 'Pancreas'], 2),
('Science', 'What is the chemical symbol for oxygen?', ARRAY['Og', 'Os', 'Ox', 'O'], 3),
('Science', 'How many chromosomes do humans have in total?', ARRAY['23', '44', '46', '48'], 2),
('Science', 'What are animals with backbones called?', ARRAY['Invertebrates', 'Vertebrates', 'Mammals', 'Amphibians'], 1),
('Science', 'What is the study of volcanoes called?', ARRAY['Seismology', 'Meteorology', 'Geology', 'Volcanology'], 3),
('Science', 'Which planet is closest in size to Earth?', ARRAY['Mars', 'Venus', 'Mercury', 'Neptune'], 1),
('Science', 'What is the unit of force?', ARRAY['Joule', 'Watt', 'Newton', 'Pascal'], 2),
('Science', 'What do caterpillars turn into?', ARRAY['Butterflies', 'Beetles', 'Spiders', 'Worms'], 0),
('Science', 'What is the scientific name for the human species?', ARRAY['Homo erectus', 'Homo sapiens', 'Homo habilis', 'Homo neanderthalensis'], 1),
('Science', 'How many different elements make up water?', ARRAY['One', 'Three', 'Two', 'Four'], 2),
('Science', 'What is the name of Earth''s natural satellite?', ARRAY['Titan', 'Europa', 'Phobos', 'The Moon'], 3),
('Science', 'What type of energy does a moving car have?', ARRAY['Nuclear', 'Potential', 'Chemical', 'Kinetic'], 3),
('Science', 'Which part of the brain controls balance and coordination?', ARRAY['Cerebrum', 'Cerebellum', 'Brain stem', 'Amygdala'], 1),
('Science', 'What is the chemical symbol for carbon?', ARRAY['C', 'Ca', 'Co', 'Cn'], 0),
('Science', 'What is the smallest planet in our solar system?', ARRAY['Pluto', 'Mars', 'Mercury', 'Venus'], 2),
('Science', 'What is the study of insects called?', ARRAY['Ornithology', 'Herpetology', 'Ichthyology', 'Entomology'], 3),
('Science', 'What is the average core temperature of the human body?', ARRAY['40°C', '37°C', '35°C', '32°C'], 1),
('Science', 'What is the first element on the periodic table?', ARRAY['Helium', 'Lithium', 'Hydrogen', 'Oxygen'], 2),
('Science', 'Which animal can change color to blend into its surroundings?', ARRAY['Camel', 'Penguin', 'Koala', 'Chameleon'], 3),
('Science', 'What is the layer of gases surrounding Earth called?', ARRAY['Hydrosphere', 'Atmosphere', 'Lithosphere', 'Biosphere'], 1),
('Science', 'What is the unit of energy?', ARRAY['Volt', 'Ampere', 'Joule', 'Ohm'], 2),
('Science', 'What kind of animal is a bat?', ARRAY['Bird', 'Reptile', 'Mammal', 'Amphibian'], 2),
('Science', 'What is it called when water turns into vapor?', ARRAY['Condensation', 'Evaporation', 'Precipitation', 'Freezing'], 1),
('Science', 'Which element has the chemical symbol "He"?', ARRAY['Hydrogen', 'Neon', 'Lithium', 'Helium'], 3),
('Science', 'What is the largest bird in the world?', ARRAY['Eagle', 'Emu', 'Ostrich', 'Albatross'], 2),
('Science', 'What is the study of earthquakes called?', ARRAY['Volcanology', 'Meteorology', 'Geology', 'Seismology'], 3),
('Science', 'Which gas do plants take in during photosynthesis?', ARRAY['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Methane'], 2),
('Science', 'What is the largest artery in the human body?', ARRAY['Aorta', 'Pulmonary vein', 'Vena cava', 'Carotid artery'], 0),
('Science', 'What color is a giraffe''s tongue?', ARRAY['Pink', 'Purple-black', 'Bright red', 'Orange'], 1),
('Science', 'What is the second planet from the Sun?', ARRAY['Mercury', 'Earth', 'Venus', 'Mars'], 2),
('Science', 'What is the unit of electrical resistance?', ARRAY['Volt', 'Ampere', 'Watt', 'Ohm'], 3),
('Science', 'Which vitamin is also known as ascorbic acid?', ARRAY['Vitamin D', 'Vitamin B12', 'Vitamin A', 'Vitamin C'], 3),
('Science', 'What is the scientific study of animals called?', ARRAY['Botany', 'Zoology', 'Geology', 'Astronomy'], 1),
('Science', 'How many planets are there in our solar system?', ARRAY['Seven', 'Nine', 'Eight', 'Ten'], 2),
('Science', 'What is the main source of energy for life on Earth?', ARRAY['The Moon', 'The Sun', 'Nuclear power', 'Geothermal heat'], 1),
('Science', 'What is the chemical symbol for potassium?', ARRAY['P', 'Po', 'K', 'Pt'], 2),
('Science', 'Which sea creature has three hearts and eight arms?', ARRAY['Jellyfish', 'Starfish', 'Sea horse', 'Octopus'], 3),
('Science', 'What is the unit of power?', ARRAY['Joule', 'Newton', 'Watt', 'Pascal'], 2),
('Science', 'What is the green pigment in plants called?', ARRAY['Melanin', 'Chlorophyll', 'Hemoglobin', 'Carotene'], 1),
('Science', 'What is the process of a caterpillar changing into a butterfly called?', ARRAY['Photosynthesis', 'Hibernation', 'Metamorphosis', 'Evolution'], 2),
('Science', 'Which of these is a noble gas?', ARRAY['Chlorine', 'Sodium', 'Calcium', 'Neon'], 3),
('Science', 'What is the smallest bone in the human body?', ARRAY['Femur', 'Radius', 'Stapes', 'Patella'], 2),
('Science', 'What is the study of matter and energy called?', ARRAY['Chemistry', 'Biology', 'Geology', 'Physics'], 3),
('Science', 'What type of animal is a frog?', ARRAY['Reptile', 'Mammal', 'Amphibian', 'Bird'], 2),
('Science', 'What is the main material in pencil "lead"?', ARRAY['Lead', 'Carbon', 'Coal', 'Clay'], 1),
('Science', 'How many stomachs does a cow have?', ARRAY['One', 'Two', 'Four', 'Three'], 2),
('Science', 'What is the red pigment in human blood called?', ARRAY['Chlorophyll', 'Melanin', 'Insulin', 'Hemoglobin'], 3),
('Science', 'What is the third planet from the Sun?', ARRAY['Venus', 'Mars', 'Earth', 'Mercury'], 2),
('Science', 'What is the scientific name for the windpipe?', ARRAY['Bronchi', 'Esophagus', 'Trachea', 'Larynx'], 2),
('Science', 'Which planet is known as the Blue Planet?', ARRAY['Neptune', 'Earth', 'Uranus', 'Saturn'], 1),
('Science', 'What is the main component of natural gas?', ARRAY['Ethane', 'Propane', 'Butane', 'Methane'], 3),
('Science', 'How many chambers does the human heart have?', ARRAY['Two', 'Three', 'Four', 'Six'], 2);

  end if;
end;
$$;


-- ============================================================================
--  MATH (110)
-- ============================================================================
do $$
begin
  if (select count(*) from public.questions where category = 'Math') < 100 then
    insert into public.questions (category, question, options, correct_index) values

('Math', 'What is 12 × 12?', ARRAY['144', '124', '132', '154'], 0),
('Math', 'What is 50% of 250?', ARRAY['100', '125', '150', '175'], 1),
('Math', 'What is the value of 5 factorial (5!)?', ARRAY['60', '100', '120', '140'], 2),
('Math', 'What is 25% of 80?', ARRAY['25', '15', '30', '20'], 3),
('Math', 'What is 11 × 11?', ARRAY['111', '121', '131', '112'], 1),
('Math', 'What is the square root of 81?', ARRAY['8', '9', '7', '11'], 1),
('Math', 'What is 1/4 written as a decimal?', ARRAY['0.75', '0.4', '0.14', '0.25'], 3),
('Math', 'What is the sum of all the numbers from 1 to 10?', ARRAY['50', '45', '55', '60'], 2),
('Math', 'What is 6 × 7?', ARRAY['40', '48', '36', '42'], 3),
('Math', 'What is 10% of 350?', ARRAY['35', '30', '45', '25'], 0),
('Math', 'What is 3 raised to the power of 3?', ARRAY['9', '18', '27', '36'], 2),
('Math', 'What is the perimeter of a square with side length 5?', ARRAY['25', '10', '15', '20'], 3),
('Math', 'What is the area of a rectangle that is 4 by 6?', ARRAY['24', '20', '28', '10'], 0),
('Math', 'What is 13 × 3?', ARRAY['33', '39', '36', '43'], 1),
('Math', 'What is 1000 divided by 8?', ARRAY['120', '130', '125', '115'], 2),
('Math', 'How many sides does a hexagon have?', ARRAY['5', '6', '7', '8'], 1),
('Math', 'What is 7 + 8 × 2?', ARRAY['30', '22', '23', '28'], 2),
('Math', 'What is 8 × 9?', ARRAY['64', '74', '68', '72'], 3),
('Math', 'What is 5/10 written as a percentage?', ARRAY['10%', '25%', '75%', '50%'], 3),
('Math', 'What is the cube root of 27?', ARRAY['2', '6', '3', '9'], 2),
('Math', 'What is 144 divided by 12?', ARRAY['11', '12', '13', '10'], 1),
('Math', 'What is 20% of 300?', ARRAY['60', '40', '80', '50'], 0),
('Math', 'How many degrees are in a right angle?', ARRAY['45', '180', '60', '90'], 3),
('Math', 'What is 9 × 6?', ARRAY['54', '48', '56', '63'], 0),
('Math', 'What number comes next: 2, 4, 8, 16, ?', ARRAY['24', '30', '32', '36'], 2),
('Math', 'What is 40 × 5?', ARRAY['200', '150', '250', '180'], 0),
('Math', 'What is 0.5 written as a fraction?', ARRAY['1/3', '1/2', '1/4', '2/3'], 1),
('Math', 'What is 15 + 27?', ARRAY['40', '44', '42', '38'], 2),
('Math', 'What is the area of a triangle with base 6 and height 4?', ARRAY['24', '10', '12', '14'], 2),
('Math', 'What is 7 × 11?', ARRAY['87', '67', '71', '77'], 3),
('Math', 'What is the value of x if x + 5 = 12?', ARRAY['5', '17', '6', '7'], 3),
('Math', 'What is 25 × 4?', ARRAY['90', '100', '110', '125'], 1),
('Math', 'How many minutes are there in a day?', ARRAY['1440', '1240', '1540', '1640'], 0),
('Math', 'What is 64 divided by 8?', ARRAY['7', '9', '8', '6'], 2),
('Math', 'What is 3/4 written as a percentage?', ARRAY['75%', '60%', '45%', '85%'], 0),
('Math', 'What is the square root of 100?', ARRAY['9', '11', '12', '10'], 3),
('Math', 'What is 17 + 19?', ARRAY['34', '38', '36', '32'], 2),
('Math', 'What is 5 × 13?', ARRAY['55', '65', '60', '70'], 1),
('Math', 'What is the circumference of a circle with diameter 10? (π ≈ 3.14)', ARRAY['31.4', '3.14', '314', '62.8'], 0),
('Math', 'What is 12 × 8?', ARRAY['92', '88', '104', '96'], 3),
('Math', 'What is 2/5 written as a decimal?', ARRAY['0.25', '0.4', '0.5', '0.2'], 1),
('Math', 'What is 100 − 27?', ARRAY['77', '83', '67', '73'], 3),
('Math', 'What is the next prime number after 13?', ARRAY['15', '19', '17', '21'], 2),
('Math', 'What is 30 × 30?', ARRAY['600', '900', '1200', '300'], 1),
('Math', 'What is 1/2 + 1/4?', ARRAY['2/6', '3/4', '1/6', '2/4'], 1),
('Math', 'How many degrees are in a full circle?', ARRAY['180', '270', '90', '360'], 3),
('Math', 'What is 11 × 12?', ARRAY['132', '121', '142', '112'], 0),
('Math', 'What is 500 divided by 25?', ARRAY['25', '15', '20', '30'], 2),
('Math', 'What is the value of 2 to the power of 4?', ARRAY['8', '32', '16', '64'], 2),
('Math', 'What is 7 × 12?', ARRAY['84', '74', '94', '78'], 0),
('Math', 'What is 15% of 60?', ARRAY['12', '9', '6', '15'], 1),
('Math', 'What is 48 divided by 6?', ARRAY['6', '7', '8', '9'], 2),
('Math', 'What is the average of 4, 8 and 12?', ARRAY['6', '10', '7', '8'], 3),
('Math', 'What is 33 + 47?', ARRAY['84', '70', '90', '80'], 3),
('Math', 'What is 9 × 11?', ARRAY['98', '99', '89', '109'], 1),
('Math', 'How many degrees are in a straight line?', ARRAY['90', '360', '270', '180'], 3),
('Math', 'What is 0.75 written as a fraction in simplest form?', ARRAY['3/4', '7/5', '15/20', '1/4'], 0),
('Math', 'What is 6 squared?', ARRAY['12', '30', '36', '42'], 2),
('Math', 'What is 125 divided by 5?', ARRAY['25', '20', '15', '35'], 0),
('Math', 'What is 14 × 6?', ARRAY['88', '74', '78', '84'], 3),
('Math', 'What is the sum of the first five prime numbers?', ARRAY['26', '28', '30', '32'], 1),
('Math', 'What is 19 × 4?', ARRAY['76', '72', '80', '84'], 0),
('Math', 'What is 5% of 400?', ARRAY['25', '15', '20', '30'], 2),
('Math', 'What is the square root of 169?', ARRAY['12', '14', '13', '11'], 2),
('Math', 'What is 3 × 15?', ARRAY['35', '45', '50', '40'], 1),
('Math', 'What is 1/3 written as a decimal (approx)?', ARRAY['0.34', '0.3', '0.33', '0.333'], 3),
('Math', 'What is 450 + 250?', ARRAY['650', '800', '700', '750'], 2),
('Math', 'What is 8 × 11?', ARRAY['86', '88', '98', '84'], 1),
('Math', 'What is 7 × 13?', ARRAY['84', '98', '91', '87'], 2),
('Math', 'What is 20 × 20?', ARRAY['400', '200', '800', '40'], 0),
('Math', 'What is 60 divided by 12?', ARRAY['6', '4', '5', '7'], 2),
('Math', 'What is 12 × 15?', ARRAY['170', '180', '150', '190'], 1),
('Math', 'What is the value of 3 to the power of 4?', ARRAY['27', '64', '12', '81'], 3),
('Math', 'What is 13 × 13?', ARRAY['156', '169', '186', '149'], 1),
('Math', 'What is 240 divided by 8?', ARRAY['30', '25', '40', '35'], 0),
('Math', 'What is 10 × 10 × 10?', ARRAY['100', '1000', '10000', '300'], 1),
('Math', 'What is 1/8 written as a decimal?', ARRAY['0.25', '0.18', '0.15', '0.125'], 3),
('Math', 'What is 35 + 46?', ARRAY['71', '81', '91', '75'], 1),
('Math', 'What is 22 × 3?', ARRAY['63', '66', '72', '56'], 1),
('Math', 'What is the area of a square with side length 9?', ARRAY['81', '72', '18', '36'], 0),
('Math', 'What is 17 × 5?', ARRAY['75', '95', '85', '80'], 2),
('Math', 'What is 1000 − 450?', ARRAY['550', '650', '450', '600'], 0),
('Math', 'What is 0.2 written as a fraction?', ARRAY['2/10', '1/5', '2/5', '1/2'], 1),
('Math', 'What is 16 × 4?', ARRAY['64', '60', '68', '54'], 0),
('Math', 'What is 7 × 9?', ARRAY['56', '61', '63', '72'], 2),
('Math', 'What is 25% of 240?', ARRAY['50', '80', '40', '60'], 3),
('Math', 'What is 1/5 written as a percentage?', ARRAY['15%', '20%', '25%', '10%'], 1),
('Math', 'What is 5 × 16?', ARRAY['90', '75', '80', '70'], 2),
('Math', 'What is 36 divided by 9?', ARRAY['3', '4', '5', '6'], 1),
('Math', 'What is 2 × 3 × 4?', ARRAY['18', '12', '32', '24'], 3),
('Math', 'What is 90 + 90?', ARRAY['160', '200', '170', '180'], 3),
('Math', 'What is the square root of 225?', ARRAY['25', '15', '45', '35'], 1),
('Math', 'What is 40% of 150?', ARRAY['40', '80', '60', '70'], 2),
('Math', 'What is 27 divided by 3?', ARRAY['8', '7', '9', '6'], 2),
('Math', 'What is 4 × 4 × 4?', ARRAY['64', '48', '32', '16'], 0),
('Math', 'What is 12 × 9?', ARRAY['98', '108', '118', '96'], 1),
('Math', 'What is 55 + 45?', ARRAY['90', '110', '95', '100'], 3),
('Math', 'What is 8 × 8?', ARRAY['56', '64', '72', '60'], 1),
('Math', 'What is 3/10 written as a percentage?', ARRAY['33%', '3%', '30%', '13%'], 2),
('Math', 'What is 15 × 15?', ARRAY['255', '205', '225', '215'], 2),
('Math', 'What is the difference between 200 and 75?', ARRAY['125', '135', '115', '175'], 0),
('Math', 'What is 6 × 11?', ARRAY['61', '72', '56', '66'], 3),
('Math', 'What is 1/6 written as a decimal (approx)?', ARRAY['0.167', '0.16', '0.176', '0.5'], 0),
('Math', 'What is 14 + 28?', ARRAY['40', '44', '42', '38'], 2),
('Math', 'What is 7 × 7?', ARRAY['42', '56', '49', '63'], 2),
('Math', 'What is 120 divided by 10?', ARRAY['10', '11', '12', '15'], 2),
('Math', 'What is 9 × 13?', ARRAY['117', '107', '127', '97'], 0),
('Math', 'What is 60% of 90?', ARRAY['60', '45', '50', '54'], 3),
('Math', 'What is 44 + 56?', ARRAY['90', '100', '110', '120'], 1),
('Math', 'What is 3 × 21?', ARRAY['63', '61', '66', '58'], 0);

  end if;
end;
$$;


-- ============================================================================
--  FOOTBALL (110)
-- ============================================================================
do $$
begin
  if (select count(*) from public.questions where category = 'Football') < 100 then
    insert into public.questions (category, question, options, correct_index) values

('Football', 'In which country did modern football (soccer) originate?', ARRAY['Brazil', 'England', 'Italy', 'Spain'], 1),
('Football', 'How many match officials are on the pitch during a standard game?', ARRAY['One', 'Two', 'Three', 'Four'], 2),
('Football', 'How often is the FIFA World Cup held?', ARRAY['Every 2 years', 'Every 3 years', 'Every 4 years', 'Every 5 years'], 2),
('Football', 'What does a yellow card mean?', ARRAY['A warning', 'A goal', 'A penalty', 'Sent off'], 0),
('Football', 'Which club plays its home games at Old Trafford?', ARRAY['Liverpool', 'Manchester United', 'Arsenal', 'Chelsea'], 1),
('Football', 'What is the name of Brazil''s most famous national stadium?', ARRAY['Maracanã', 'Estádio da Luz', 'Wembley', 'La Bombonera'], 0),
('Football', 'Which position usually wears the number 1 shirt?', ARRAY['Striker', 'Midfielder', 'Defender', 'Goalkeeper'], 3),
('Football', 'Which national team is nicknamed "La Albiceleste"?', ARRAY['Mexico', 'Uruguay', 'Colombia', 'Argentina'], 3),
('Football', 'What is the name of the top division of English football?', ARRAY['La Liga', 'Premier League', 'Serie A', 'Bundesliga'], 1),
('Football', 'Which Italian club is nicknamed "The Old Lady"?', ARRAY['AC Milan', 'Inter Milan', 'Juventus', 'Napoli'], 2),
('Football', 'Who is the all-time top scorer in FIFA World Cup history (men''s)?', ARRAY['Pele', 'Ronaldo', 'Miroslav Klose', 'Gerd Muller'], 2),
('Football', 'What is a "derby" match?', ARRAY['A game between local rivals', 'A cup final', 'A friendly match', 'A match against a foreign club'], 0),
('Football', 'Which national team is nicknamed "The Three Lions"?', ARRAY['Scotland', 'Wales', 'England', 'Ireland'], 2),
('Football', 'In a knockout match tied after 90 minutes, what happens next?', ARRAY['Golden goal', 'Extra time', 'The match is replayed', 'A coin toss'], 1),
('Football', 'Which city hosted the 2014 World Cup final?', ARRAY['Rio de Janeiro', 'Sao Paulo', 'Brasilia', 'Belo Horizonte'], 0),
('Football', 'What is the width of a standard football goal?', ARRAY['6.32 m', '7.32 m', '8.32 m', '9.32 m'], 1),
('Football', 'Which Brazilian legend is nicknamed "The King of Football"?', ARRAY['Ronaldinho', 'Ronaldo', 'Pele', 'Neymar'], 2),
('Football', 'What does VAR stand for?', ARRAY['Video Assistant Referee', 'Virtual Arena Review', 'Visual Assistant Replay', 'Verified Action Referee'], 0),
('Football', 'Which club is nicknamed "The Gunners"?', ARRAY['Tottenham', 'Arsenal', 'Chelsea', 'West Ham'], 1),
('Football', 'How long is the halftime break in a standard match?', ARRAY['5 minutes', '10 minutes', '15 minutes', '20 minutes'], 2),
('Football', 'Which South American national team is nicknamed "La Celeste"?', ARRAY['Peru', 'Argentina', 'Chile', 'Uruguay'], 3),
('Football', 'Which club has won the most European Cups / Champions League titles?', ARRAY['Barcelona', 'AC Milan', 'Bayern Munich', 'Real Madrid'], 3),
('Football', 'Which Argentine legend won the 1986 World Cup almost single-handedly?', ARRAY['Lionel Messi', 'Diego Maradona', 'Gabriel Batistuta', 'Carlos Tevez'], 1),
('Football', 'What is the German national team commonly called?', ARRAY['Die Mannschaft', 'Los Blancos', 'The Red Devils', 'La Furia Roja'], 0),
('Football', 'Which English club plays at Anfield?', ARRAY['Everton', 'Liverpool', 'Manchester City', 'Newcastle'], 1),
('Football', 'What is the distance from the penalty spot to the goal?', ARRAY['9 meters', '10 meters', '11 meters', '12 meters'], 2),
('Football', 'Which player is nicknamed "CR7"?', ARRAY['Cristiano Ronaldo', 'Ronaldinho', 'Roberto Carlos', 'Ronaldo Nazario'], 0),
('Football', 'What does a red card mean?', ARRAY['A warning', 'The player is sent off', 'A free kick for the other side', 'The goal is disallowed'], 1),
('Football', 'Which club is known as "Los Blancos"?', ARRAY['Atletico Madrid', 'Sevilla', 'Barcelona', 'Real Madrid'], 3),
('Football', 'What is a "clean sheet"?', ARRAY['A match with no goals conceded', 'A brand new pitch', 'A win by 3 goals', 'A goal scored from a corner'], 0),
('Football', 'Which Spanish club plays at the Camp Nou?', ARRAY['Real Madrid', 'Barcelona', 'Valencia', 'Sevilla'], 1),
('Football', 'What is the world governing body of football?', ARRAY['UEFA', 'CONMEBOL', 'FIFA', 'AFC'], 2),
('Football', 'Which country won the 2018 FIFA World Cup?', ARRAY['Croatia', 'Germany', 'Belgium', 'France'], 3),
('Football', 'What is the name of Europe''s top club competition?', ARRAY['Europa League', 'UEFA Champions League', 'Conference League', 'Cup Winners Cup'], 1),
('Football', 'Which Brazilian striker is nicknamed "The Phenomenon"?', ARRAY['Rivaldo', 'Kaka', 'Romario', 'Ronaldo (R9)'], 3),
('Football', 'What is the name of England''s national stadium?', ARRAY['Old Trafford', 'Emirates', 'Wembley', 'St James Park'], 2),
('Football', 'In which year did Brazil win their first World Cup?', ARRAY['1950', '1958', '1962', '1970'], 1),
('Football', 'What is the name of Italy''s top division?', ARRAY['Ligue 1', 'La Liga', 'Bundesliga', 'Serie A'], 3),
('Football', 'Which club is nicknamed "The Toffees"?', ARRAY['Liverpool', 'Everton', 'Leeds', 'Aston Villa'], 1),
('Football', 'What does "FC" stand for?', ARRAY['Football Club', 'Famous Club', 'Final Champion', 'Forward Center'], 0),
('Football', 'Which country''s top league is called La Liga?', ARRAY['Portugal', 'Italy', 'Spain', 'France'], 2),
('Football', 'What is the name of the trophy awarded to the winners of the European Championship?', ARRAY['Henri Delaunay Cup', 'Jules Rimet Cup', 'Golden Trophy', 'Continental Cup'], 0),
('Football', 'Which Argentine forward has won the most Ballon d''Or awards?', ARRAY['Diego Maradona', 'Lionel Messi', 'Alfredo Di Stefano', 'Sergio Aguero'], 1),
('Football', 'What is a "volley" in football?', ARRAY['Hitting the ball before it bounces', 'A pass backwards', 'A header from a corner', 'A shot from the halfway line'], 0),
('Football', 'Which club plays at the Allianz Arena?', ARRAY['Borussia Dortmund', 'RB Leipzig', 'Bayern Munich', 'Schalke'], 2),
('Football', 'Which national team is nicknamed "The Oranje"?', ARRAY['Belgium', 'Denmark', 'Norway', 'Netherlands'], 3),
('Football', 'What is it called when a player scores into their own team''s goal?', ARRAY['Ghost goal', 'Reverse goal', 'Self goal', 'Own goal'], 3),
('Football', 'In which year was the English Premier League founded?', ARRAY['1988', '1990', '1992', '1995'], 2),
('Football', 'Which country won Euro 2020 (played in 2021)?', ARRAY['England', 'Spain', 'France', 'Italy'], 3),
('Football', 'Which national team is nicknamed "The Samba Boys"?', ARRAY['Brazil', 'Portugal', 'Argentina', 'Colombia'], 0),
('Football', 'What is a "nutmeg" in football?', ARRAY['A tackle from behind', 'Playing the ball through an opponent''s legs', 'A goal from a corner', 'A penalty save'], 1),
('Football', 'Which Spanish club plays at the Metropolitano?', ARRAY['Real Madrid', 'Atletico Madrid', 'Barcelona', 'Real Betis'], 1),
('Football', 'How many teams play in the English Premier League?', ARRAY['18', '20', '22', '24'], 1),
('Football', 'What is the award for the top scorer at a World Cup called?', ARRAY['Golden Boot', 'Golden Glove', 'Golden Ball', 'Golden Head'], 0),
('Football', 'Which player scored the famous "Hand of God" goal?', ARRAY['Pele', 'Lionel Messi', 'Diego Maradona', 'Zinedine Zidane'], 2),
('Football', 'What is the name of France''s top division?', ARRAY['Serie A', 'Eredivisie', 'Primeira Liga', 'Ligue 1'], 3),
('Football', 'Which London club plays at Stamford Bridge?', ARRAY['Chelsea', 'Arsenal', 'Tottenham', 'Fulham'], 0),
('Football', 'Which country won the 2022 FIFA World Cup?', ARRAY['France', 'Brazil', 'Argentina', 'Croatia'], 2),
('Football', 'What is the name of Germany''s top division?', ARRAY['Premier League', 'Serie A', 'La Liga', 'Bundesliga'], 3),
('Football', 'Which club is nicknamed "The Pensioners"?', ARRAY['Arsenal', 'Chelsea', 'West Ham', 'Crystal Palace'], 1),
('Football', 'When is a corner kick awarded?', ARRAY['When the attacking team misses a shot', 'When the defending team puts the ball out behind its own goal line', 'When a foul happens', 'After a goal'], 1),
('Football', 'Who holds the record for most goals in a single World Cup (13)?', ARRAY['Just Fontaine', 'Pele', 'Gerd Muller', 'Ronaldo'], 0),
('Football', 'Which country hosted the 2022 World Cup?', ARRAY['Saudi Arabia', 'Qatar', 'UAE', 'Turkey'], 1),
('Football', 'What is the name of the big match between Real Madrid and Barcelona?', ARRAY['El Clasico', 'The Derby', 'The Final', 'La Supercopa'], 0),
('Football', 'Which Manchester club plays in sky blue?', ARRAY['Manchester United', 'Manchester City', 'Bolton', 'Salford City'], 1),
('Football', 'What is the height of a standard football goal?', ARRAY['2.44 m', '2.14 m', '2.84 m', '3.44 m'], 0),
('Football', 'Which national team is nicknamed "The Super Eagles"?', ARRAY['Ghana', 'Senegal', 'Nigeria', 'Ivory Coast'], 2),
('Football', 'Which club has won the most FA Cup titles?', ARRAY['Manchester United', 'Arsenal', 'Liverpool', 'Chelsea'], 1),
('Football', 'What is the player who leads the team on the pitch called?', ARRAY['The coach', 'The captain', 'The referee', 'The keeper'], 1),
('Football', 'Which country won the 2006 FIFA World Cup?', ARRAY['France', 'Brazil', 'Italy', 'Germany'], 2),
('Football', 'What is the name of the Netherlands'' top division?', ARRAY['Allsvenskan', 'Jupiler League', 'Primeira Liga', 'Eredivisie'], 3),
('Football', 'Which Brazilian club is nicknamed "O Peixe" (The Fish)?', ARRAY['Flamengo', 'Santos', 'Palmeiras', 'Corinthians'], 1),
('Football', 'What is a "rabona"?', ARRAY['A backheel pass', 'Kicking the ball with the leg wrapped behind the standing leg', 'A penalty feint', 'A diving header'], 1),
('Football', 'Which Italian star was nicknamed "The Divine Ponytail"?', ARRAY['Roberto Baggio', 'Alessandro Del Piero', 'Francesco Totti', 'Paolo Maldini'], 0),
('Football', 'Which national team is nicknamed "The Indomitable Lions"?', ARRAY['Senegal', 'Morocco', 'Cameroon', 'Algeria'], 2),
('Football', 'If a knockout match is still level after extra time, what decides the winner?', ARRAY['Penalty shootout', 'Golden goal', 'A replay', 'The away goals rule'], 0),
('Football', 'Which club plays at the Parc des Princes?', ARRAY['Lyon', 'Marseille', 'Monaco', 'Paris Saint-Germain'], 3),
('Football', 'What is the nickname of Italy''s national team?', ARRAY['Gli Azzurri', 'La Roja', 'Die Mannschaft', 'Les Bleus'], 0),
('Football', 'Who won the Golden Ball as best player of the 2022 World Cup?', ARRAY['Kylian Mbappe', 'Lionel Messi', 'Luka Modric', 'Julian Alvarez'], 1),
('Football', 'What is the maximum number of points a Premier League team can get in one season?', ARRAY['102', '110', '114', '120'], 2),
('Football', 'Which country won the 1998 FIFA World Cup?', ARRAY['France', 'Brazil', 'Italy', 'Argentina'], 0),
('Football', 'What is the name of Japan''s top football division?', ARRAY['K-League', 'J.League', 'A-League', 'CSL'], 1),
('Football', 'Which club is nicknamed "The Cottagers"?', ARRAY['Crystal Palace', 'Brighton', 'Brentford', 'Fulham'], 3),
('Football', 'What is a goal scored directly from a corner kick called?', ARRAY['A free goal', 'An olimpico', 'A bicycle goal', 'A golden corner'], 1),
('Football', 'Which national team is nicknamed "The Black Stars"?', ARRAY['Nigeria', 'Cameroon', 'Ghana', 'Egypt'], 2),
('Football', 'Which club won the first Champions League under that name (1992-93)?', ARRAY['Marseille', 'AC Milan', 'Real Madrid', 'Ajax'], 0),
('Football', 'How many times has Brazil won the FIFA World Cup?', ARRAY['Four', 'Five', 'Six', 'Three'], 1),
('Football', 'What is the name of Portugal''s top division?', ARRAY['Primeira Liga', 'La Liga', 'Serie A', 'Eredivisie'], 0),
('Football', 'Which national team is nicknamed "The Red Devils"?', ARRAY['France', 'Belgium', 'England', 'Denmark'], 1),
('Football', 'What is a "cross" in football?', ARRAY['A pass into the penalty area from the wing', 'A pass backwards to the keeper', 'A foul in midfield', 'A corner save'], 0),
('Football', 'Which club plays at Signal Iduna Park?', ARRAY['Bayern Munich', 'Borussia Dortmund', 'Leverkusen', 'Frankfurt'], 1),
('Football', 'Which country''s top league is called the MLS?', ARRAY['Mexico', 'Canada', 'United States', 'Brazil'], 2),
('Football', 'What was the mascot of the 2014 World Cup called?', ARRAY['Zakumi', 'Fuleco', 'Zabivaka', 'Naranjito'], 1),
('Football', 'Which club is nicknamed "The Red and Black" (Rossoneri)?', ARRAY['Lazio', 'Inter Milan', 'Roma', 'AC Milan'], 3),
('Football', 'What is a "Panenka" penalty?', ARRAY['A powerful low shot', 'A chipped kick down the middle', 'A shot into the corner', 'A stutter-step shot'], 1),
('Football', 'Which country won the 1966 FIFA World Cup?', ARRAY['Germany', 'Portugal', 'England', 'Brazil'], 2),
('Football', 'What is the award for the best goalkeeper at a World Cup called?', ARRAY['Golden Boot', 'Golden Ball', 'Golden Glove', 'Golden Save'], 2),
('Football', 'Which Italian club plays in black and white stripes?', ARRAY['Juventus', 'Inter', 'Roma', 'Fiorentina'], 0),
('Football', 'Which national team is nicknamed "The Blue Samurai"?', ARRAY['South Korea', 'Japan', 'China', 'Thailand'], 1),
('Football', 'Which stadium hosted the 2022 World Cup final?', ARRAY['Khalifa Stadium', 'Lusail Stadium', 'Al Bayt Stadium', 'Stadium 974'], 1),
('Football', 'Which legendary Brazilian was nicknamed "The Black Pearl"?', ARRAY['Pele', 'Garrincha', 'Socrates', 'Zico'], 0),
('Football', 'How many European places did the World Cup have in 2022?', ARRAY['13', '11', '15', '9'], 0),
('Football', 'What is the name of Brazil''s top football league?', ARRAY['Copa Libertadores', 'Primera Division', 'Serie A', 'Campeonato Brasileiro'], 3),
('Football', 'What is a "dead ball" situation?', ARRAY['A ball that has gone out of play', 'A restart from a stop such as a free kick or corner', 'A ball stuck in the net', 'A throw-in taken slowly'], 1),
('Football', 'Who scored the winning goal in extra time of the 2014 World Cup final?', ARRAY['Mario Gotze', 'Thomas Muller', 'Andre Schurrle', 'Miroslav Klose'], 0),
('Football', 'What is the award for the best player at a World Cup called?', ARRAY['Golden Boot', 'Golden Glove', 'Golden Ball', 'Golden Captain'], 2),
('Football', 'Which club is nicknamed "The Lilywhites"?', ARRAY['Tottenham Hotspur', 'Leeds United', 'West Brom', 'Norwich'], 0),
('Football', 'Which national team is nicknamed "The Socceroos"?', ARRAY['Australia', 'New Zealand', 'South Africa', 'Ireland'], 0),
('Football', 'Which country won the 2010 FIFA World Cup?', ARRAY['Netherlands', 'Germany', 'Spain', 'Uruguay'], 2),
('Football', 'Which club is nicknamed "The Hornets"?', ARRAY['Sunderland', 'Norwich', 'Bournemouth', 'Watford'], 3);

  end if;
end;
$$;


-- ============================================================================
--  HISTORY (110)
-- ============================================================================
do $$
begin
  if (select count(*) from public.questions where category = 'History') < 100 then
    insert into public.questions (category, question, options, correct_index) values

('History', 'In which year did World War I begin?', ARRAY['1912', '1913', '1914', '1915'], 2),
('History', 'Who was the first Emperor of Rome?', ARRAY['Julius Caesar', 'Augustus', 'Nero', 'Trajan'], 1),
('History', 'Which ancient civilization built Machu Picchu?', ARRAY['Aztec', 'Maya', 'Inca', 'Olmec'], 2),
('History', 'Who reached the Americas in 1492?', ARRAY['Christopher Columbus', 'Ferdinand Magellan', 'Vasco da Gama', 'John Cabot'], 0),
('History', 'In which year did the American Civil War end?', ARRAY['1863', '1864', '1865', '1866'], 2),
('History', 'Who was the British Prime Minister during most of World War II?', ARRAY['Neville Chamberlain', 'Winston Churchill', 'Clement Attlee', 'Anthony Eden'], 1),
('History', 'What was the name of the ship that carried the Pilgrims to America in 1620?', ARRAY['Mayflower', 'Santa Maria', 'Endeavour', 'Beagle'], 0),
('History', 'Which empire built the Colosseum in Rome?', ARRAY['Greek', 'Egyptian', 'Persian', 'Roman'], 3),
('History', 'In which year did the French Revolution begin?', ARRAY['1789', '1776', '1799', '1815'], 0),
('History', 'Who was the first woman to fly solo across the Atlantic?', ARRAY['Harriet Quimby', 'Bessie Coleman', 'Jacqueline Cochran', 'Amelia Earhart'], 3),
('History', 'What divided East and West Berlin for decades?', ARRAY['The Rhine', 'The Berlin Wall', 'An electric fence', 'A river'], 1),
('History', 'Who was the main author of the US Declaration of Independence?', ARRAY['George Washington', 'Benjamin Franklin', 'Thomas Jefferson', 'John Adams'], 2),
('History', 'In which year did the Soviet Union dissolve?', ARRAY['1989', '1990', '1991', '1993'], 2),
('History', 'Which of the Seven Wonders stood in Babylon?', ARRAY['Hanging Gardens', 'Colossus', 'Lighthouse of Alexandria', 'Statue of Zeus'], 0),
('History', 'Who was the Egyptian queen who allied with Mark Antony?', ARRAY['Nefertiti', 'Cleopatra', 'Hatshepsut', 'Ramses'' wife'], 1),
('History', 'In which year did humans first walk on the Moon?', ARRAY['1965', '1967', '1969', '1971'], 2),
('History', 'Which British leader was known as the "Iron Lady"?', ARRAY['Margaret Thatcher', 'Queen Victoria', 'Angela Merkel', 'Theresa May'], 0),
('History', 'Which dynasty is credited with starting the Great Wall of China?', ARRAY['Han', 'Tang', 'Ming', 'Qin'], 3),
('History', 'Who was the Soviet leader during the Cuban Missile Crisis?', ARRAY['Joseph Stalin', 'Leonid Brezhnev', 'Nikita Khrushchev', 'Mikhail Gorbachev'], 2),
('History', 'What was the deadly 1918 influenza outbreak called?', ARRAY['Spanish Flu', 'Asian Flu', 'Swine Flu', 'Cholera'], 0),
('History', 'Who painted the ceiling of the Sistine Chapel?', ARRAY['Leonardo da Vinci', 'Michelangelo', 'Raphael', 'Donatello'], 1),
('History', 'Who was the last reigning queen of Hawaii?', ARRAY['Queen Liliuokalani', 'Queen Kaahumanu', 'Queen Emma', 'Queen Kapiolani'], 0),
('History', 'Who led the first expedition to reach the South Pole?', ARRAY['Robert Falcon Scott', 'Roald Amundsen', 'Ernest Shackleton', 'James Cook'], 1),
('History', 'Which empire was ruled by Emperor Hirohito during World War II?', ARRAY['Japan', 'Germany', 'Italy', 'Ottoman Empire'], 0),
('History', 'What was the name of the US program that landed men on the Moon?', ARRAY['Mercury', 'Gemini', 'Apollo', 'Voyager'], 2),
('History', 'Who was the Roman god of war?', ARRAY['Jupiter', 'Mars', 'Neptune', 'Apollo'], 1),
('History', 'In which year did the United States declare independence?', ARRAY['1775', '1776', '1777', '1781'], 1),
('History', 'Who founded the Mongol Empire?', ARRAY['Kublai Khan', 'Genghis Khan', 'Attila', 'Timur'], 1),
('History', 'What was the capital of the Inca Empire?', ARRAY['Lima', 'Machu Picchu', 'Cusco', 'Quito'], 2),
('History', 'Who co-wrote "The Communist Manifesto" with Friedrich Engels?', ARRAY['Karl Marx', 'Vladimir Lenin', 'Joseph Stalin', 'Rosa Luxemburg'], 0),
('History', 'In which year did the Great Fire of London take place?', ARRAY['1642', '1666', '1688', '1701'], 1),
('History', 'Who was the first president of the Republic of China?', ARRAY['Mao Zedong', 'Chiang Kai-shek', 'Sun Yat-sen', 'Yuan Shikai'], 2),
('History', 'Which ancient civilization is famous for hieroglyphics?', ARRAY['Ancient Egypt', 'Ancient Greece', 'Ancient Rome', 'Ancient Persia'], 0),
('History', 'Who is credited with inventing the telephone?', ARRAY['Thomas Edison', 'Alexander Graham Bell', 'Nikola Tesla', 'Guglielmo Marconi'], 1),
('History', 'What treaty ended World War I?', ARRAY['Treaty of Rome', 'Treaty of Paris', 'Treaty of Ghent', 'Treaty of Versailles'], 3),
('History', 'Who was the last emperor of China?', ARRAY['Qianlong', 'Puyi', 'Kangxi', 'Hongwu'], 1),
('History', 'In which year did the United States enter World War II?', ARRAY['1939', '1940', '1941', '1942'], 2),
('History', 'Who discovered penicillin?', ARRAY['Louis Pasteur', 'Alexander Fleming', 'Marie Curie', 'Edward Jenner'], 1),
('History', 'What was the name of the first artificial satellite?', ARRAY['Sputnik 1', 'Explorer 1', 'Vostok 1', 'Telstar'], 0),
('History', 'Which Roman emperor officially opened the Colosseum?', ARRAY['Vespasian', 'Titus', 'Domitian', 'Nero'], 1),
('History', 'In which year did the Spanish Armada sail against England?', ARRAY['1620', '1566', '1601', '1588'], 3),
('History', 'Who is known as the "father of the atomic bomb"?', ARRAY['Albert Einstein', 'Enrico Fermi', 'J. Robert Oppenheimer', 'Niels Bohr'], 2),
('History', 'What wall did the Romans build across northern Britain?', ARRAY['Hadrian''s Wall', 'Antonine Wall', 'Offa''s Dyke', 'The Great Wall'], 0),
('History', 'Who was the first female Prime Minister of India?', ARRAY['Indira Gandhi', 'Benazir Bhutto', 'Margaret Thatcher', 'Golda Meir'], 0),
('History', 'In which year was the United Nations founded?', ARRAY['1943', '1944', '1945', '1946'], 2),
('History', 'Who explored the Louisiana Territory for the United States?', ARRAY['Lewis and Clark', 'Daniel Boone', 'Meriwether Lewis only', 'Zebulon Pike'], 0),
('History', 'Which US conflict was fought between the North and the South?', ARRAY['Revolutionary War', 'Civil War', 'War of 1812', 'Spanish-American War'], 1),
('History', 'Who was the English queen during the defeat of the Spanish Armada?', ARRAY['Mary I', 'Elizabeth I', 'Victoria', 'Anne'], 1),
('History', 'In which year did the Korean War begin?', ARRAY['1948', '1949', '1950', '1953'], 2),
('History', 'Which ancient people developed the first known writing system (cuneiform)?', ARRAY['Phoenicians', 'Egyptians', 'Greeks', 'Sumerians'], 3),
('History', 'Who was the first person to walk on the Moon?', ARRAY['Buzz Aldrin', 'Neil Armstrong', 'Michael Collins', 'Yuri Gagarin'], 1),
('History', 'Who was the Inca emperor captured by the Spanish in 1533?', ARRAY['Atahualpa', 'Huayna Capac', 'Manco Capac', 'Tupac Amaru'], 0),
('History', 'Who is credited with writing the epic poems "The Iliad" and "The Odyssey"?', ARRAY['Socrates', 'Plato', 'Homer', 'Sophocles'], 2),
('History', 'In which year did Fidel Castro take power in Cuba?', ARRAY['1953', '1956', '1959', '1962'], 2),
('History', 'Who was the leader of Nazi Germany?', ARRAY['Adolf Hitler', 'Benito Mussolini', 'Joseph Goebbels', 'Heinrich Himmler'], 0),
('History', 'On which ship was the Japanese surrender signed in 1945?', ARRAY['USS Missouri', 'USS Arizona', 'HMS Prince of Wales', 'USS Enterprise'], 0),
('History', 'Who was the first European to reach India by sea?', ARRAY['Christopher Columbus', 'Vasco da Gama', 'Ferdinand Magellan', 'James Cook'], 1),
('History', 'Which empire was known as the "Land of the Rising Sun"?', ARRAY['China', 'Korea', 'Japan', 'Siam'], 2),
('History', 'In which year did the American Revolution formally end?', ARRAY['1776', '1781', '1783', '1789'], 2),
('History', 'Who is famous for developing the practical incandescent light bulb?', ARRAY['Thomas Edison', 'Nikola Tesla', 'James Watt', 'Benjamin Franklin'], 0),
('History', 'What was the capital of the Aztec Empire?', ARRAY['Cusco', 'Chichen Itza', 'Tenochtitlan', 'Teotihuacan'], 2),
('History', 'Who was the English king defeated at the Battle of Hastings?', ARRAY['Edward the Confessor', 'Harold Godwinson', 'William Rufus', 'Henry I'], 1),
('History', 'In which year was the Battle of Hastings?', ARRAY['1042', '1066', '1087', '1100'], 1),
('History', 'In which year did the Great Depression begin?', ARRAY['1925', '1927', '1929', '1931'], 2),
('History', 'Who was the Greek philosopher who tutored Alexander the Great?', ARRAY['Socrates', 'Plato', 'Aristotle', 'Pythagoras'], 2),
('History', 'What was the US plan to rebuild Europe after World War II called?', ARRAY['Truman Doctrine', 'Marshall Plan', 'New Deal', 'Lend-Lease'], 1),
('History', 'Who was the first emperor of a unified China?', ARRAY['Liu Bang', 'Qin Shi Huang', 'Wu Zetian', 'Sun Tzu'], 1),
('History', 'What was the ancient trade route connecting East and West called?', ARRAY['Royal Road', 'Spice Route', 'Amber Road', 'Silk Road'], 3),
('History', 'Which nurse became famous during the Crimean War?', ARRAY['Florence Nightingale', 'Mary Seacole', 'Clara Barton', 'Edith Cavell'], 0),
('History', 'In which year did the Vietnam War end with the fall of Saigon?', ARRAY['1973', '1974', '1975', '1976'], 2),
('History', 'Which English king was forced to sign the Magna Carta in 1215?', ARRAY['Richard the Lionheart', 'King John', 'Henry III', 'William the Conqueror'], 1),
('History', 'Which famous conqueror rode the horse Bucephalus?', ARRAY['Julius Caesar', 'Alexander the Great', 'Hannibal', 'Genghis Khan'], 1),
('History', 'In which year did the United States buy Alaska from Russia?', ARRAY['1867', '1877', '1857', '1897'], 0),
('History', 'Who was the Soviet leader during most of World War II?', ARRAY['Vladimir Lenin', 'Joseph Stalin', 'Nikita Khrushchev', 'Leon Trotsky'], 1),
('History', 'What was the writing system of ancient Egypt called?', ARRAY['Cuneiform', 'Hieroglyphics', 'Runes', 'Linear B'], 1),
('History', 'Who was the first African-American president of the United States?', ARRAY['Martin Luther King Jr.', 'Barack Obama', 'Colin Powell', 'Frederick Douglass'], 1),
('History', 'In which year was the European Union established by the Maastricht Treaty?', ARRAY['1990', '1991', '1992', '1993'], 3),
('History', 'Who was the Greek goddess of wisdom?', ARRAY['Hera', 'Athena', 'Aphrodite', 'Artemis'], 1),
('History', 'Which English king was executed in 1649?', ARRAY['Charles I', 'Charles II', 'James I', 'Henry VIII'], 0),
('History', 'Who invented the European printing press with movable type?', ARRAY['Galileo Galilei', 'William Caxton', 'Leonardo da Vinci', 'Johannes Gutenberg'], 3),
('History', 'In which year did the Hundred Years'' War end?', ARRAY['1421', '1431', '1453', '1485'], 2),
('History', 'Who was the first woman to win a Nobel Prize?', ARRAY['Marie Curie', 'Rosalind Franklin', 'Mother Teresa', 'Jane Addams'], 0),
('History', 'Which ancient Roman city was buried by the eruption of Vesuvius?', ARRAY['Rome', 'Pompeii', 'Ostia', 'Carthage'], 1),
('History', 'Who was the Egyptian boy king whose tomb was found intact in 1922?', ARRAY['Ramses II', 'Tutankhamun', 'Akhenaten', 'Seti I'], 1),
('History', 'In which year did the Space Shuttle Challenger disaster occur?', ARRAY['1984', '1985', '1986', '1987'], 2),
('History', 'Who commanded the British forces that defeated Napoleon at Waterloo?', ARRAY['Lord Nelson', 'Duke of Wellington', 'General Wolfe', 'Lord Kitchener'], 1),
('History', 'In which year did the Spanish conquest of the Aztec capital end?', ARRAY['1492', '1519', '1521', '1533'], 2),
('History', 'Who wrote the epic poem "The Aeneid"?', ARRAY['Homer', 'Virgil', 'Ovid', 'Horace'], 1),
('History', 'In which year did World War II begin?', ARRAY['1937', '1938', '1939', '1940'], 2),
('History', 'Who became the first Black president of South Africa after apartheid?', ARRAY['Desmond Tutu', 'Nelson Mandela', 'Thabo Mbeki', 'F. W. de Klerk'], 1),
('History', 'In which year was the Berlin Wall built?', ARRAY['1959', '1961', '1963', '1965'], 1),
('History', 'Which Soviet leader introduced glasnost and perestroika?', ARRAY['Leonid Brezhnev', 'Yuri Andropov', 'Mikhail Gorbachev', 'Boris Yeltsin'], 2),
('History', 'Which French queen was executed during the Revolution?', ARRAY['Marie Antoinette', 'Catherine de Medici', 'Anne of Austria', 'Josephine'], 0),
('History', 'Who was the legendary king of the Huns?', ARRAY['Theodoric', 'Alaric', 'Odoacer', 'Attila'], 3),
('History', 'In which year did the American Revolutionary War begin?', ARRAY['1773', '1774', '1775', '1776'], 2),
('History', 'Who was the Roman general who became "dictator for life"?', ARRAY['Pompey', 'Julius Caesar', 'Augustus', 'Sulla'], 1),
('History', 'Which ancient culture created the Nazca Lines in Peru?', ARRAY['Inca', 'Nazca', 'Moche', 'Chavin'], 1),
('History', 'Who is considered the first Prime Minister of Great Britain?', ARRAY['Robert Walpole', 'William Pitt', 'Henry Pelham', 'Lord North'], 0),
('History', 'In which year did the Crimean War end?', ARRAY['1854', '1855', '1856', '1857'], 2),
('History', 'Which Greek philosopher was sentenced to death by drinking hemlock?', ARRAY['Plato', 'Aristotle', 'Socrates', 'Epicurus'], 2),
('History', 'What was the name of the German air force in World War II?', ARRAY['Wehrmacht', 'Luftwaffe', 'Kriegsmarine', 'Gestapo'], 1),
('History', 'Who was the great female pharaoh of ancient Egypt?', ARRAY['Nefertiti', 'Hatshepsut', 'Cleopatra', 'Merneith'], 1),
('History', 'In which year did the Russo-Japanese War end?', ARRAY['1904', '1905', '1906', '1907'], 1),
('History', 'Who led the Continental Army and became the first US president?', ARRAY['George Washington', 'Thomas Jefferson', 'John Adams', 'Alexander Hamilton'], 0),
('History', 'What was the central public square of ancient Rome called?', ARRAY['Forum', 'Agora', 'Campus', 'Circus'], 0),
('History', 'Who was the first Englishman to circumnavigate the globe?', ARRAY['John Smith', 'Walter Raleigh', 'Henry Hudson', 'Francis Drake'], 3),
('History', 'In which year did the Soviet Union launch Sputnik?', ARRAY['1955', '1956', '1957', '1958'], 2),
('History', 'Who was the last emperor of the Western Roman Empire?', ARRAY['Romulus Augustulus', 'Theodosius', 'Constantine', 'Honorius'], 0),
('History', 'Who gave the famous "I Have a Dream" speech?', ARRAY['Malcolm X', 'Martin Luther King Jr.', 'Rosa Parks', 'Jesse Jackson'], 1),
('History', 'In which year was the Battle of Waterloo fought?', ARRAY['1805', '1812', '1815', '1818'], 2);

  end if;
end;
$$;


-- ============================================================================
--  DONE!  Total question bank: 40 (seed.sql) + 440 (this file) = 480 questions
--  across Science / Math / Football / History.  Re-running this file is safe.
-- ============================================================================
